### ISSUE TITLE
Eyed Theme not Showing

### ISSUE THREAD

**Issue by XCOD33** [febryars33/eyed-phpmyadmin-theme#1]
![image](https://user-images.githubusercontent.com/33880217/208119035-5eb837ef-12ae-4dbf-95ab-adaeb3edb4ff.png)

**Comment by reeyanto** [comment]
phpmyadmin versi berapa?

**Comment by reeyanto** [comment]
> ![image](https://user-images.githubusercontent.com/33880217/208119035-5eb837ef-12ae-4dbf-95ab-adaeb3edb4ff.png)
> 

phpmyadmin versi berapa?

**Comment by febryars33** [comment]
Untuk versi phpMyAdmin 5.2

**Comment by febryars33** [comment]
Apakah versi phpMyAdmin nya udah 5.2?

**Comment by XCOD33** [comment]
5.1.1 ternyata. Makasih udah edit README
