### ISSUE TITLE
Out-dated UI in Designer Tab

### ISSUE THREAD

**Issue by HashenUdara** [febryars33/eyed-phpmyadmin-theme#2]
in this designer tab 
<img width="957" alt="Screenshot 2022-12-17 135737" src="https://user-images.githubusercontent.com/106765093/208233212-f3e36731-b5cd-4355-b924-b164f31cc57f.png">

There is still an outdated UI, and also update these icons.
Thank you.
<img width="960" alt="Screenshot 2022-12-17 134935" src="https://user-images.githubusercontent.com/106765093/208233308-91d6c9e0-24e7-4ba4-819b-225c39debfaf.png">

**Comment by febryars33** [comment]
Okay thanks, i'll change it 👍

**Comment by febryars33** [comment]
![chrome_l5bG6jABpR](https://user-images.githubusercontent.com/48888849/208341286-0a4442e8-49c6-4e3e-8580-249552fddd68.png)
@HashenUdara like this ?

**Comment by HashenUdara** [comment]
It's awesome @febryars33 
Already it's like windows 11 fluent design or stuff like that.
Here I am some suggestions for improve that

**Comment by HashenUdara** [comment]
It's awesome @febryars33 


Already it's like windows 11 fluent design or stuff like that.
Here I am some suggestions for improve that.
In these elements
![208341286-0a4442e8-49c6-4e3e-8580-249552fddd68](https://user-images.githubusercontent.com/106765093/208350515-5baf288b-0e65-45a8-920c-15e5e64e0efe.png)

 Remove border (` border: none`) or change to 1px or something like that
 Add border radius around 8px
  Change the down arrow in the elements top bar

**Comment by febryars33** [comment]
![chrome_uC6EIg0WUz](https://user-images.githubusercontent.com/48888849/208368708-1f961a75-9277-450e-8b09-9f5f5ef9bcd8.png)

Done..
Like this ? 😃

**Comment by HashenUdara** [comment]
Love that. 🔥

**Comment by febryars33** [comment]
Thanks :)
