### ISSUE TITLE
Active Tab Background Color 

### ISSUE THREAD

**Issue by HashenUdara** [febryars33/eyed-phpmyadmin-theme#3]
It is difficult to find out which is the active tab in this theme.
When we switch to the 'pmahomme' theme. Active tabs are easy to find.
Change the background color of tab active state.

<img width="618" alt="Screenshot 2022-12-17 140841" src="https://user-images.githubusercontent.com/106765093/208233872-677d134b-6bd2-4834-b0a7-7897e4250e46.png">

<img width="607" alt="Screenshot 2022-12-17 140723" src="https://user-images.githubusercontent.com/106765093/208233789-77f39fd5-70d6-4114-b3c7-215334ec3fb2.png">

**Comment by febryars33** [comment]
Okay thanks, i'll change it 👍

**Comment by febryars33** [comment]
![chrome_l5bG6jABpR](https://user-images.githubusercontent.com/48888849/208341286-0a4442e8-49c6-4e3e-8580-249552fddd68.png)
@HashenUdara like this ?
